### ISSUE TITLE
License violations

### ISSUE THREAD

**Issue by dracc** [NicusorN5/VCMP-Zombie-Survival#2]
server64.exe is not licensed under a compatible license for this project - it should not be redistributed here.

**Comment by NicusorN5** [comment]
Pffft seriously? Who cares lmfao. Already planned to remove it, but i will keep it in order to easily debug the scripts.

**Comment by dracc** [comment]
A serious programmer cares.
It's not like it's hard to add it to the `.gitignore` file and letting it stay in that folder locally on your machine.
Users not running Windows won't be helped by having it either, the opposite is more likely - "Why can't I start the server on my Ubuntu based VPS?"

**Comment by dracc** [comment]
Friendly reminder of bullet nr 2 in the CoC you've added to this repository yourself;
"`* Being respectful of differing viewpoints and experiences`"
